### ISSUE TITLE
Mouse pointer não é mais o custom

### ISSUE THREAD

**Issue by lmatiolis** [CoalaTech/nonsensenoir#1]

**Comment by claudiovicar** [comment]
Estou ciente desse bug. Quando fui mudar as URLs pra nova estrutura de pastas vi que, do jeito que está feito, o CreateJS faz uma requisição pra cada movimento do mouse, fica inviável. Isso já foi um problema antes, temos que ver como corrigir.

**Comment by claudiovicar** [comment]
Pensei num negocio aqui, talvez tentar usar uma imagem em base64 resolva. Vou tentar quando der.

**Comment by claudiovicar** [comment]
Corrigido, realmente a imagem codificada como base64 resolveu. Tentei fechar a issue direto no commit mas parece que não deu certo....será que é só quando fizer merge na master?

**Comment by lmatiolis** [comment]
@claudiovicar "For example, a commit message with Fixes #45 will close issue 45 in that repository once the commit is merged into the default branch."

Podemos colocar nossa default branch pra develop, já que jogaremos na master só versões mais completas.

**Comment by lmatiolis** [comment]
Alterei aqui mas não reconheceu a alteração não. Mas os próximos commits vão dar certo sim! ;)

Vou fechar a issue então.

**Comment by claudiovicar** [comment]
Acho que é isso mesmo, os próximos devem funcionar =]
