### ISSUE TITLE
Sobre namespaces e o padrão prototype

### ISSUE THREAD

**Issue by claudiovicar** [CoalaTech/nonsensenoir#4]
Pesquisando um pouco sobre os namespaces, gostei bem do jeito que é feito no createjs. É bem simples, cada arquivo declara:

```
this.createjs = this.createjs||{};

createjs.Classe = function(){...},
```

 onde o _this_ ali é o _window_. Acho que podemos fazer assim com o _this.nsn_ =]

---

Sobre o prototype, andei vendo uns issues no repositório do createjs e eles conseguiram um bom ganho de performance declarando as _propriedades_ na função construtora da classe e os métodos em si no protótipo dessa função. Acho que a gente podia seguir essa linha pra padronizar.

Tem um PR lá sobre isso: https://github.com/CreateJS/EaselJS/pull/509

Vou deixar registrado aqui pra não esquecer =]
Basicamente, ao invés de

```
var Player = function(){...};

Player.prototype._bitmap = null;

Player.prototype.walk = function(){...};
```

faz-se

```
var Player = function(){
    this._bitmap = null;
};
Player.prototype.walk = function(){...};
```

**Comment by claudiovicar** [comment]
Isso deveria ser uma issue? Agora é.

**Comment by lmatiolis** [comment]
Podemos alterar a ideia dela pra fazer essas alterações no código e ai quando finalizar, fechar essa issue! ;)

**Comment by lmatiolis** [comment]
Fechada com merge da `feature_prototype` na master. (Esqueci de botar o closes na mensagem do commit de merge). O commit foi: b00795d769951f1845c79735e395b4f95787bea9
